// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bdsw_user_service.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc.api;

@com.google.protobuf.Generated
public final class BdswUserServiceProto extends com.google.protobuf.GeneratedFile {
  private BdswUserServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      BdswUserServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bdsw_muc_api_TokenReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bdsw_muc_api_TokenReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bdsw_muc_api_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bdsw_muc_api_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027bdsw_user_service.proto\022\014bdsw.muc.api\"" +
      "\031\n\010TokenReq\022\r\n\005token\030\001 \001(\t\".\n\010UserInfo\022\017" +
      "\n\007user_id\030\001 \001(\t\022\021\n\tuser_name\030\002 \001(\t2P\n\017Bd" +
      "swUserService\022=\n\013verifyToken\022\026.bdsw.muc." +
      "api.TokenReq\032\026.bdsw.muc.api.UserInfoB*\n\020" +
      "com.bdsw.muc.apiB\024BdswUserServiceProtoP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_bdsw_muc_api_TokenReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bdsw_muc_api_TokenReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bdsw_muc_api_TokenReq_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_bdsw_muc_api_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bdsw_muc_api_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bdsw_muc_api_UserInfo_descriptor,
        new java.lang.String[] { "UserId", "UserName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
