// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bdsw_user_service.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc.api;

@com.google.protobuf.Generated
public interface TokenReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bdsw.muc.api.TokenReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 字段编号，从 1 开始
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * 字段编号，从 1 开始
   * </pre>
   *
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
