// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.common;

@com.google.protobuf.Generated
public final class CommonProto extends com.google.protobuf.GeneratedFile {
  private CommonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      CommonProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_common_BaseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_common_BaseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_common_PageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_common_PageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_common_PageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_common_PageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_common_DeviceInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_common_DeviceInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_common_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_common_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_common_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_common_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bdsw_common_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bdsw_common_ServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\017com.bdsw.common\"Q\n\014BaseR" +
      "esponse\022\017\n\007success\030\001 \001(\010\022\014\n\004code\030\002 \001(\t\022\017" +
      "\n\007message\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\"U\n\013Pa" +
      "geRequest\022\014\n\004page\030\001 \001(\005\022\021\n\tpage_size\030\002 \001" +
      "(\005\022\022\n\nsort_field\030\003 \001(\t\022\021\n\tsort_desc\030\004 \001(" +
      "\010\"S\n\014PageResponse\022\r\n\005total\030\001 \001(\005\022\014\n\004page" +
      "\030\002 \001(\005\022\021\n\tpage_size\030\003 \001(\005\022\023\n\013total_pages" +
      "\030\004 \001(\005\"\237\001\n\nDeviceInfo\022\021\n\tdevice_id\030\001 \001(\t" +
      "\022\023\n\013device_type\030\002 \001(\t\022\024\n\014device_brand\030\003 " +
      "\001(\t\022\024\n\014device_model\030\004 \001(\t\022\022\n\nos_version\030" +
      "\005 \001(\t\022\023\n\013app_version\030\006 \001(\t\022\024\n\014network_ty" +
      "pe\030\007 \001(\t\"\211\001\n\010UserInfo\022\017\n\007user_id\030\001 \001(\t\022\020" +
      "\n\010username\030\002 \001(\t\022\020\n\010nickname\030\003 \001(\t\022\016\n\006av" +
      "atar\030\004 \001(\t\022\016\n\006status\030\005 \001(\005\022\023\n\013create_tim" +
      "e\030\006 \001(\003\022\023\n\013update_time\030\007 \001(\003\"\225\001\n\rClientM" +
      "essage\022\022\n\nmessage_id\030\001 \001(\t\022\017\n\007user_id\030\002 " +
      "\001(\t\022\014\n\004type\030\003 \001(\t\022\016\n\006action\030\004 \001(\t\022\014\n\004dat" +
      "a\030\005 \001(\014\022\021\n\ttimestamp\030\006 \001(\003\022\r\n\005token\030\007 \001(" +
      "\t\022\021\n\tdevice_id\030\010 \001(\t\"\205\001\n\rServerMessage\022\022" +
      "\n\nmessage_id\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\016\n\006acti" +
      "on\030\003 \001(\t\022\014\n\004data\030\004 \001(\014\022\021\n\ttimestamp\030\005 \001(" +
      "\003\022\016\n\006status\030\006 \001(\t\022\021\n\terror_msg\030\007 \001(\tBN\n\017" +
      "com.bdsw.commonB\013CommonProtoP\001Z,github.c" +
      "om/bdsw/bdsw-im-ws/api/common;commonb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bdsw_common_BaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bdsw_common_BaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_common_BaseResponse_descriptor,
        new java.lang.String[] { "Success", "Code", "Message", "Timestamp", });
    internal_static_com_bdsw_common_PageRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bdsw_common_PageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_common_PageRequest_descriptor,
        new java.lang.String[] { "Page", "PageSize", "SortField", "SortDesc", });
    internal_static_com_bdsw_common_PageResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bdsw_common_PageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_common_PageResponse_descriptor,
        new java.lang.String[] { "Total", "Page", "PageSize", "TotalPages", });
    internal_static_com_bdsw_common_DeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_bdsw_common_DeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_common_DeviceInfo_descriptor,
        new java.lang.String[] { "DeviceId", "DeviceType", "DeviceBrand", "DeviceModel", "OsVersion", "AppVersion", "NetworkType", });
    internal_static_com_bdsw_common_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_bdsw_common_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_common_UserInfo_descriptor,
        new java.lang.String[] { "UserId", "Username", "Nickname", "Avatar", "Status", "CreateTime", "UpdateTime", });
    internal_static_com_bdsw_common_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_bdsw_common_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_common_ClientMessage_descriptor,
        new java.lang.String[] { "MessageId", "UserId", "Type", "Action", "Data", "Timestamp", "Token", "DeviceId", });
    internal_static_com_bdsw_common_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_bdsw_common_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_bdsw_common_ServerMessage_descriptor,
        new java.lang.String[] { "MessageId", "Type", "Action", "Data", "Timestamp", "Status", "ErrorMsg", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
