// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.common;

@com.google.protobuf.Generated
public interface DeviceInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.common.DeviceInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   * web, android, ios, windows, mac
   * </pre>
   *
   * <code>string device_type = 2;</code>
   * @return The deviceType.
   */
  java.lang.String getDeviceType();
  /**
   * <pre>
   * web, android, ios, windows, mac
   * </pre>
   *
   * <code>string device_type = 2;</code>
   * @return The bytes for deviceType.
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();

  /**
   * <code>string device_brand = 3;</code>
   * @return The deviceBrand.
   */
  java.lang.String getDeviceBrand();
  /**
   * <code>string device_brand = 3;</code>
   * @return The bytes for deviceBrand.
   */
  com.google.protobuf.ByteString
      getDeviceBrandBytes();

  /**
   * <code>string device_model = 4;</code>
   * @return The deviceModel.
   */
  java.lang.String getDeviceModel();
  /**
   * <code>string device_model = 4;</code>
   * @return The bytes for deviceModel.
   */
  com.google.protobuf.ByteString
      getDeviceModelBytes();

  /**
   * <code>string os_version = 5;</code>
   * @return The osVersion.
   */
  java.lang.String getOsVersion();
  /**
   * <code>string os_version = 5;</code>
   * @return The bytes for osVersion.
   */
  com.google.protobuf.ByteString
      getOsVersionBytes();

  /**
   * <code>string app_version = 6;</code>
   * @return The appVersion.
   */
  java.lang.String getAppVersion();
  /**
   * <code>string app_version = 6;</code>
   * @return The bytes for appVersion.
   */
  com.google.protobuf.ByteString
      getAppVersionBytes();

  /**
   * <code>string network_type = 7;</code>
   * @return The networkType.
   */
  java.lang.String getNetworkType();
  /**
   * <code>string network_type = 7;</code>
   * @return The bytes for networkType.
   */
  com.google.protobuf.ByteString
      getNetworkTypeBytes();
}
