// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.common;

@com.google.protobuf.Generated
public interface PageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.common.PageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 page_size = 2;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>string sort_field = 3;</code>
   * @return The sortField.
   */
  java.lang.String getSortField();
  /**
   * <code>string sort_field = 3;</code>
   * @return The bytes for sortField.
   */
  com.google.protobuf.ByteString
      getSortFieldBytes();

  /**
   * <code>bool sort_desc = 4;</code>
   * @return The sortDesc.
   */
  boolean getSortDesc();
}
