// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.common;

@com.google.protobuf.Generated
public interface PageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.common.PageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 total = 1;</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <code>int32 page = 2;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 page_size = 3;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>int32 total_pages = 4;</code>
   * @return The totalPages.
   */
  int getTotalPages();
}
