// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.common;

@com.google.protobuf.Generated
public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.common.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string nickname = 3;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 3;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string avatar = 4;</code>
   * @return The avatar.
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 4;</code>
   * @return The bytes for avatar.
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <pre>
   * 用户状态
   * </pre>
   *
   * <code>int32 status = 5;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int64 create_time = 6;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <code>int64 update_time = 7;</code>
   * @return The updateTime.
   */
  long getUpdateTime();
}
