// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: muc.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc;

/**
 * <pre>
 * 获取用户权限响应
 * </pre>
 *
 * Protobuf type {@code com.bdsw.muc.GetUserPermissionsResponse}
 */
@com.google.protobuf.Generated
public final class GetUserPermissionsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.bdsw.muc.GetUserPermissionsResponse)
    GetUserPermissionsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      GetUserPermissionsResponse.class.getName());
  }
  // Use GetUserPermissionsResponse.newBuilder() to construct.
  private GetUserPermissionsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetUserPermissionsResponse() {
    permissions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.bdsw.muc.MucProto.internal_static_com_bdsw_muc_GetUserPermissionsResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 3:
        return internalGetFeatureFlags();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.bdsw.muc.MucProto.internal_static_com_bdsw_muc_GetUserPermissionsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.bdsw.muc.GetUserPermissionsResponse.class, com.bdsw.muc.GetUserPermissionsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASE_FIELD_NUMBER = 1;
  private com.bdsw.common.BaseResponse base_;
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  @java.lang.Override
  public boolean hasBase() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  @java.lang.Override
  public com.bdsw.common.BaseResponse getBase() {
    return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
  }
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  @java.lang.Override
  public com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder() {
    return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
  }

  public static final int PERMISSIONS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList permissions_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string permissions = 2;</code>
   * @return A list containing the permissions.
   */
  public com.google.protobuf.ProtocolStringList
      getPermissionsList() {
    return permissions_;
  }
  /**
   * <code>repeated string permissions = 2;</code>
   * @return The count of permissions.
   */
  public int getPermissionsCount() {
    return permissions_.size();
  }
  /**
   * <code>repeated string permissions = 2;</code>
   * @param index The index of the element to return.
   * @return The permissions at the given index.
   */
  public java.lang.String getPermissions(int index) {
    return permissions_.get(index);
  }
  /**
   * <code>repeated string permissions = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the permissions at the given index.
   */
  public com.google.protobuf.ByteString
      getPermissionsBytes(int index) {
    return permissions_.getByteString(index);
  }

  public static final int FEATURE_FLAGS_FIELD_NUMBER = 3;
  private static final class FeatureFlagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.Boolean> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.Boolean>newDefaultInstance(
                com.bdsw.muc.MucProto.internal_static_com_bdsw_muc_GetUserPermissionsResponse_FeatureFlagsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BOOL,
                false);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.Boolean> featureFlags_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
  internalGetFeatureFlags() {
    if (featureFlags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          FeatureFlagsDefaultEntryHolder.defaultEntry);
    }
    return featureFlags_;
  }
  public int getFeatureFlagsCount() {
    return internalGetFeatureFlags().getMap().size();
  }
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  @java.lang.Override
  public boolean containsFeatureFlags(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetFeatureFlags().getMap().containsKey(key);
  }
  /**
   * Use {@link #getFeatureFlagsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlags() {
    return getFeatureFlagsMap();
  }
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlagsMap() {
    return internalGetFeatureFlags().getMap();
  }
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  @java.lang.Override
  public boolean getFeatureFlagsOrDefault(
      java.lang.String key,
      boolean defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetFeatureFlags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  @java.lang.Override
  public boolean getFeatureFlagsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.Boolean> map =
        internalGetFeatureFlags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBase());
    }
    for (int i = 0; i < permissions_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, permissions_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetFeatureFlags(),
        FeatureFlagsDefaultEntryHolder.defaultEntry,
        3);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBase());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < permissions_.size(); i++) {
        dataSize += computeStringSizeNoTag(permissions_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPermissionsList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.Boolean> entry
         : internalGetFeatureFlags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
      featureFlags__ = FeatureFlagsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, featureFlags__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.bdsw.muc.GetUserPermissionsResponse)) {
      return super.equals(obj);
    }
    com.bdsw.muc.GetUserPermissionsResponse other = (com.bdsw.muc.GetUserPermissionsResponse) obj;

    if (hasBase() != other.hasBase()) return false;
    if (hasBase()) {
      if (!getBase()
          .equals(other.getBase())) return false;
    }
    if (!getPermissionsList()
        .equals(other.getPermissionsList())) return false;
    if (!internalGetFeatureFlags().equals(
        other.internalGetFeatureFlags())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBase()) {
      hash = (37 * hash) + BASE_FIELD_NUMBER;
      hash = (53 * hash) + getBase().hashCode();
    }
    if (getPermissionsCount() > 0) {
      hash = (37 * hash) + PERMISSIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPermissionsList().hashCode();
    }
    if (!internalGetFeatureFlags().getMap().isEmpty()) {
      hash = (37 * hash) + FEATURE_FLAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetFeatureFlags().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.bdsw.muc.GetUserPermissionsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.bdsw.muc.GetUserPermissionsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.bdsw.muc.GetUserPermissionsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.bdsw.muc.GetUserPermissionsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 获取用户权限响应
   * </pre>
   *
   * Protobuf type {@code com.bdsw.muc.GetUserPermissionsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.bdsw.muc.GetUserPermissionsResponse)
      com.bdsw.muc.GetUserPermissionsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bdsw.muc.MucProto.internal_static_com_bdsw_muc_GetUserPermissionsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetFeatureFlags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableFeatureFlags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bdsw.muc.MucProto.internal_static_com_bdsw_muc_GetUserPermissionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bdsw.muc.GetUserPermissionsResponse.class, com.bdsw.muc.GetUserPermissionsResponse.Builder.class);
    }

    // Construct using com.bdsw.muc.GetUserPermissionsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBaseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      permissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableFeatureFlags().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.bdsw.muc.MucProto.internal_static_com_bdsw_muc_GetUserPermissionsResponse_descriptor;
    }

    @java.lang.Override
    public com.bdsw.muc.GetUserPermissionsResponse getDefaultInstanceForType() {
      return com.bdsw.muc.GetUserPermissionsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.bdsw.muc.GetUserPermissionsResponse build() {
      com.bdsw.muc.GetUserPermissionsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.bdsw.muc.GetUserPermissionsResponse buildPartial() {
      com.bdsw.muc.GetUserPermissionsResponse result = new com.bdsw.muc.GetUserPermissionsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.bdsw.muc.GetUserPermissionsResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.base_ = baseBuilder_ == null
            ? base_
            : baseBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        permissions_.makeImmutable();
        result.permissions_ = permissions_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.featureFlags_ = internalGetFeatureFlags();
        result.featureFlags_.makeImmutable();
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.bdsw.muc.GetUserPermissionsResponse) {
        return mergeFrom((com.bdsw.muc.GetUserPermissionsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.bdsw.muc.GetUserPermissionsResponse other) {
      if (other == com.bdsw.muc.GetUserPermissionsResponse.getDefaultInstance()) return this;
      if (other.hasBase()) {
        mergeBase(other.getBase());
      }
      if (!other.permissions_.isEmpty()) {
        if (permissions_.isEmpty()) {
          permissions_ = other.permissions_;
          bitField0_ |= 0x00000002;
        } else {
          ensurePermissionsIsMutable();
          permissions_.addAll(other.permissions_);
        }
        onChanged();
      }
      internalGetMutableFeatureFlags().mergeFrom(
          other.internalGetFeatureFlags());
      bitField0_ |= 0x00000004;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBaseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensurePermissionsIsMutable();
              permissions_.add(s);
              break;
            } // case 18
            case 26: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Boolean>
              featureFlags__ = input.readMessage(
                  FeatureFlagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableFeatureFlags().getMutableMap().put(
                  featureFlags__.getKey(), featureFlags__.getValue());
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.bdsw.common.BaseResponse base_;
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder> baseBuilder_;
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     * @return Whether the base field is set.
     */
    public boolean hasBase() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     * @return The base.
     */
    public com.bdsw.common.BaseResponse getBase() {
      if (baseBuilder_ == null) {
        return base_ == null ? com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
      } else {
        return baseBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder setBase(com.bdsw.common.BaseResponse value) {
      if (baseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        base_ = value;
      } else {
        baseBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder setBase(
        com.bdsw.common.BaseResponse.Builder builderForValue) {
      if (baseBuilder_ == null) {
        base_ = builderForValue.build();
      } else {
        baseBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder mergeBase(com.bdsw.common.BaseResponse value) {
      if (baseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          base_ != null &&
          base_ != com.bdsw.common.BaseResponse.getDefaultInstance()) {
          getBaseBuilder().mergeFrom(value);
        } else {
          base_ = value;
        }
      } else {
        baseBuilder_.mergeFrom(value);
      }
      if (base_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public Builder clearBase() {
      bitField0_ = (bitField0_ & ~0x00000001);
      base_ = null;
      if (baseBuilder_ != null) {
        baseBuilder_.dispose();
        baseBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public com.bdsw.common.BaseResponse.Builder getBaseBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBaseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    public com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder() {
      if (baseBuilder_ != null) {
        return baseBuilder_.getMessageOrBuilder();
      } else {
        return base_ == null ?
            com.bdsw.common.BaseResponse.getDefaultInstance() : base_;
      }
    }
    /**
     * <code>.com.bdsw.common.BaseResponse base = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder> 
        internalGetBaseFieldBuilder() {
      if (baseBuilder_ == null) {
        baseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.bdsw.common.BaseResponse, com.bdsw.common.BaseResponse.Builder, com.bdsw.common.BaseResponseOrBuilder>(
                getBase(),
                getParentForChildren(),
                isClean());
        base_ = null;
      }
      return baseBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList permissions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePermissionsIsMutable() {
      if (!permissions_.isModifiable()) {
        permissions_ = new com.google.protobuf.LazyStringArrayList(permissions_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @return A list containing the permissions.
     */
    public com.google.protobuf.ProtocolStringList
        getPermissionsList() {
      permissions_.makeImmutable();
      return permissions_;
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @return The count of permissions.
     */
    public int getPermissionsCount() {
      return permissions_.size();
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @param index The index of the element to return.
     * @return The permissions at the given index.
     */
    public java.lang.String getPermissions(int index) {
      return permissions_.get(index);
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the permissions at the given index.
     */
    public com.google.protobuf.ByteString
        getPermissionsBytes(int index) {
      return permissions_.getByteString(index);
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @param index The index to set the value at.
     * @param value The permissions to set.
     * @return This builder for chaining.
     */
    public Builder setPermissions(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePermissionsIsMutable();
      permissions_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @param value The permissions to add.
     * @return This builder for chaining.
     */
    public Builder addPermissions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensurePermissionsIsMutable();
      permissions_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @param values The permissions to add.
     * @return This builder for chaining.
     */
    public Builder addAllPermissions(
        java.lang.Iterable<java.lang.String> values) {
      ensurePermissionsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, permissions_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPermissions() {
      permissions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string permissions = 2;</code>
     * @param value The bytes of the permissions to add.
     * @return This builder for chaining.
     */
    public Builder addPermissionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensurePermissionsIsMutable();
      permissions_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Boolean> featureFlags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
        internalGetFeatureFlags() {
      if (featureFlags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FeatureFlagsDefaultEntryHolder.defaultEntry);
      }
      return featureFlags_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.Boolean>
        internalGetMutableFeatureFlags() {
      if (featureFlags_ == null) {
        featureFlags_ = com.google.protobuf.MapField.newMapField(
            FeatureFlagsDefaultEntryHolder.defaultEntry);
      }
      if (!featureFlags_.isMutable()) {
        featureFlags_ = featureFlags_.copy();
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return featureFlags_;
    }
    public int getFeatureFlagsCount() {
      return internalGetFeatureFlags().getMap().size();
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
     */
    @java.lang.Override
    public boolean containsFeatureFlags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetFeatureFlags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFeatureFlagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlags() {
      return getFeatureFlagsMap();
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Boolean> getFeatureFlagsMap() {
      return internalGetFeatureFlags().getMap();
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
     */
    @java.lang.Override
    public boolean getFeatureFlagsOrDefault(
        java.lang.String key,
        boolean defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetFeatureFlags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
     */
    @java.lang.Override
    public boolean getFeatureFlagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Boolean> map =
          internalGetFeatureFlags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearFeatureFlags() {
      bitField0_ = (bitField0_ & ~0x00000004);
      internalGetMutableFeatureFlags().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
     */
    public Builder removeFeatureFlags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableFeatureFlags().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Boolean>
        getMutableFeatureFlags() {
      bitField0_ |= 0x00000004;
      return internalGetMutableFeatureFlags().getMutableMap();
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
     */
    public Builder putFeatureFlags(
        java.lang.String key,
        boolean value) {
      if (key == null) { throw new NullPointerException("map key"); }

      internalGetMutableFeatureFlags().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
     */
    public Builder putAllFeatureFlags(
        java.util.Map<java.lang.String, java.lang.Boolean> values) {
      internalGetMutableFeatureFlags().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000004;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.bdsw.muc.GetUserPermissionsResponse)
  }

  // @@protoc_insertion_point(class_scope:com.bdsw.muc.GetUserPermissionsResponse)
  private static final com.bdsw.muc.GetUserPermissionsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.bdsw.muc.GetUserPermissionsResponse();
  }

  public static com.bdsw.muc.GetUserPermissionsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserPermissionsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUserPermissionsResponse>() {
    @java.lang.Override
    public GetUserPermissionsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetUserPermissionsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserPermissionsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.bdsw.muc.GetUserPermissionsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

