// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: muc.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc;

@com.google.protobuf.Generated
public interface GetUserPermissionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.muc.GetUserPermissionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  com.bdsw.common.BaseResponse getBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>repeated string permissions = 2;</code>
   * @return A list containing the permissions.
   */
  java.util.List<java.lang.String>
      getPermissionsList();
  /**
   * <code>repeated string permissions = 2;</code>
   * @return The count of permissions.
   */
  int getPermissionsCount();
  /**
   * <code>repeated string permissions = 2;</code>
   * @param index The index of the element to return.
   * @return The permissions at the given index.
   */
  java.lang.String getPermissions(int index);
  /**
   * <code>repeated string permissions = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the permissions at the given index.
   */
  com.google.protobuf.ByteString
      getPermissionsBytes(int index);

  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  int getFeatureFlagsCount();
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  boolean containsFeatureFlags(
      java.lang.String key);
  /**
   * Use {@link #getFeatureFlagsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Boolean>
  getFeatureFlags();
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.Boolean>
  getFeatureFlagsMap();
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  boolean getFeatureFlagsOrDefault(
      java.lang.String key,
      boolean defaultValue);
  /**
   * <code>map&lt;string, bool&gt; feature_flags = 3;</code>
   */
  boolean getFeatureFlagsOrThrow(
      java.lang.String key);
}
