// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: muc.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc;

@com.google.protobuf.Generated
public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.muc.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string device_id = 3;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 3;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>.com.bdsw.common.DeviceInfo device_info = 4;</code>
   * @return Whether the deviceInfo field is set.
   */
  boolean hasDeviceInfo();
  /**
   * <code>.com.bdsw.common.DeviceInfo device_info = 4;</code>
   * @return The deviceInfo.
   */
  com.bdsw.common.DeviceInfo getDeviceInfo();
  /**
   * <code>.com.bdsw.common.DeviceInfo device_info = 4;</code>
   */
  com.bdsw.common.DeviceInfoOrBuilder getDeviceInfoOrBuilder();
}
