// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: muc.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc;

@com.google.protobuf.Generated
public interface RefreshTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.muc.RefreshTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  com.bdsw.common.BaseResponse getBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>string new_token = 2;</code>
   * @return The newToken.
   */
  java.lang.String getNewToken();
  /**
   * <code>string new_token = 2;</code>
   * @return The bytes for newToken.
   */
  com.google.protobuf.ByteString
      getNewTokenBytes();

  /**
   * <code>string refresh_token = 3;</code>
   * @return The refreshToken.
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refresh_token = 3;</code>
   * @return The bytes for refreshToken.
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();

  /**
   * <code>int64 expire_time = 4;</code>
   * @return The expireTime.
   */
  long getExpireTime();
}
