// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: muc.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc;

@com.google.protobuf.Generated
public interface TokenValidateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.muc.TokenValidateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return Whether the base field is set.
   */
  boolean hasBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   * @return The base.
   */
  com.bdsw.common.BaseResponse getBase();
  /**
   * <code>.com.bdsw.common.BaseResponse base = 1;</code>
   */
  com.bdsw.common.BaseResponseOrBuilder getBaseOrBuilder();

  /**
   * <code>bool valid = 2;</code>
   * @return The valid.
   */
  boolean getValid();

  /**
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>int64 expire_time = 5;</code>
   * @return The expireTime.
   */
  long getExpireTime();

  /**
   * <code>map&lt;string, string&gt; user_info = 6;</code>
   */
  int getUserInfoCount();
  /**
   * <code>map&lt;string, string&gt; user_info = 6;</code>
   */
  boolean containsUserInfo(
      java.lang.String key);
  /**
   * Use {@link #getUserInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getUserInfo();
  /**
   * <code>map&lt;string, string&gt; user_info = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getUserInfoMap();
  /**
   * <code>map&lt;string, string&gt; user_info = 6;</code>
   */
  /* nullable */
java.lang.String getUserInfoOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; user_info = 6;</code>
   */
  java.lang.String getUserInfoOrThrow(
      java.lang.String key);

  /**
   * <code>string session_id = 7;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 7;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>repeated string permissions = 8;</code>
   * @return A list containing the permissions.
   */
  java.util.List<java.lang.String>
      getPermissionsList();
  /**
   * <code>repeated string permissions = 8;</code>
   * @return The count of permissions.
   */
  int getPermissionsCount();
  /**
   * <code>repeated string permissions = 8;</code>
   * @param index The index of the element to return.
   * @return The permissions at the given index.
   */
  java.lang.String getPermissions(int index);
  /**
   * <code>repeated string permissions = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the permissions at the given index.
   */
  com.google.protobuf.ByteString
      getPermissionsBytes(int index);
}
