// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: muc.proto
// Protobuf Java Version: 4.32.1

package com.bdsw.muc;

@com.google.protobuf.Generated
public interface TokenValidateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.bdsw.muc.TokenValidateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string token = 2;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string device_id = 3;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 3;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string client_version = 4;</code>
   * @return The clientVersion.
   */
  java.lang.String getClientVersion();
  /**
   * <code>string client_version = 4;</code>
   * @return The bytes for clientVersion.
   */
  com.google.protobuf.ByteString
      getClientVersionBytes();

  /**
   * <code>string client_type = 5;</code>
   * @return The clientType.
   */
  java.lang.String getClientType();
  /**
   * <code>string client_type = 5;</code>
   * @return The bytes for clientType.
   */
  com.google.protobuf.ByteString
      getClientTypeBytes();

  /**
   * <code>.com.bdsw.muc.DeviceInfo device_info = 6;</code>
   * @return Whether the deviceInfo field is set.
   */
  boolean hasDeviceInfo();
  /**
   * <code>.com.bdsw.muc.DeviceInfo device_info = 6;</code>
   * @return The deviceInfo.
   */
  com.bdsw.muc.DeviceInfo getDeviceInfo();
  /**
   * <code>.com.bdsw.muc.DeviceInfo device_info = 6;</code>
   */
  com.bdsw.muc.DeviceInfoOrBuilder getDeviceInfoOrBuilder();
}
